# Generated by Django 4.1.6 on 2023-02-10 15:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_countrycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('house_number', models.SmallIntegerField()),
                ('flat_number', models.SmallIntegerField()),
                ('guests', models.SmallIntegerField()),
                ('rooms', models.SmallIntegerField()),
                ('beds', models.SmallIntegerField()),
                ('bathrooms', models.SmallIntegerField()),
                ('wifi', models.BooleanField()),
                ('fridge', models.BooleanField()),
                ('air_conditioner', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('furniture', models.BooleanField()),
                ('washing', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('kitchen', models.BooleanField()),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('image4', models.ImageField(blank=True, upload_to='images')),
                ('image5', models.ImageField(blank=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.CharField(choices=[('in_stock', 'активен'), ('out_of_stock', 'неактивен')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category.category')),
                ('country_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='country', to='category.countrycategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
