# Generated by Django 4.1.6 on 2023-02-21 12:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('house_number', models.PositiveSmallIntegerField()),
                ('flat_number', models.PositiveSmallIntegerField(blank=True)),
                ('guests', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('beds', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('washing', models.BooleanField(default=False)),
                ('medicine', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category.category')),
                ('country_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='country', to='category.countrycategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
