# Generated by Django 4.1.5 on 2023-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='air_conditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='flat_number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='washing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
