# Generated by Django 4.1.6 on 2023-02-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image4_alter_product_image5'),
        ('product', '0002_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
    ]
