# Generated by Django 4.1.6 on 2023-02-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='country',
        ),
    ]
