# Generated by Django 4.1.6 on 2023-02-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_countrycategory_category_ptr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycategory',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='countrycategory',
            old_name='slug1',
            new_name='slug',
        ),
    ]
