# Generated by Django 4.1.6 on 2023-02-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_name1_countrycategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycategory',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='countrycategory',
            old_name='slug',
            new_name='slug1',
        ),
    ]
